# Built-in BasicTS Model Benchmark

This section benchmarks several built-in BasicTS forecasting models on the ETTh1 dataset using the same shared settings and training procedure, then ranks them by performance.

In [1]:
# Project setup: ensure repo root and src are on the path
import os
import sys
from pathlib import Path
ROOT = Path(r"C:\Users\luwil\OneDrive\Documents\Code\BasicTS")
os.chdir(ROOT)
src_path = ROOT / "src"
if str(src_path) not in sys.path:
	sys.path.insert(0, str(src_path))

In [ ]:
# Imports and shared benchmark settings
import json
import importlib
import traceback
import pkgutil
from pathlib import Path
from math import sqrt
import pandas as pd

import torch

from basicts.configs import BasicTSForecastingConfig, BasicTSModelConfig
from basicts.launcher import BasicTSLauncher
from basicts.runners.builder import Builder
from basicts.runners.taskflow import BasicTSForecastingTaskFlow
from basicts.scaler import ZScoreScaler
from basicts.utils import BasicTSMode

# Shared dataset / training settings for the benchmark
DATASET_NAME = "ETTh1"
INPUT_LEN = 96
OUTPUT_LEN = 12
NUM_FEATURES = 7
BATCH_SIZE = 32
NUM_EPOCHS = 5
LEARNING_RATE = 1e-3

# Shared BasicTS config fields used for every model
SHARED_CONFIG = {
	"dataset_name": DATASET_NAME,
	"input_len": INPUT_LEN,
	"dataset_params": {
		"input_len": INPUT_LEN,
		"output_len": OUTPUT_LEN,
		"use_timestamps": False,
		"memmap": False,
	},
	"use_timestamps": False,
	"batch_size": BATCH_SIZE,
	"num_epochs": NUM_EPOCHS,
	"scaler": ZScoreScaler,
	"norm_each_channel": True,
	"rescale": False,
	"metrics": ["MAE", "MSE", "RMSE", "MAPE", "WAPE"],
	"optimizer_params": {"lr": LEARNING_RATE, "weight_decay": 5e-4},
	"gpus": None,
	"train_data_num_workers": 0,
	"val_data_num_workers": 0,
	"test_data_num_workers": 0,
	"save_results": True,
}

# Auto-discover model modules inside basicts.models that expose a Config and a forecasting class
import basicts.models as _models_pkg

def discover_models():
	candidates = []
	for finder, name, ispkg in pkgutil.iter_modules(_models_pkg.__path__):
		try:
			mod = importlib.import_module(f"basicts.models.{name}")
		except Exception:
			continue
		has_config = any(attr.endswith("Config") for attr in dir(mod))
		has_forecast = any("Forecast" in attr for attr in dir(mod))
		has_modelname = hasattr(mod, name)
		if has_config and (has_forecast or has_modelname):
			candidates.append(name)
	return sorted(candidates)

discovered = discover_models()
print("Discovered model modules:", discovered)

# User-requested selection: 3 simple and 3 advanced models (in priority order)
DESIRED_SIMPLE = ["DLinear", "NLinear", "MTSMixer"]
DESIRED_ADVANCED = ["TimesNet", "iTransformer", "PatchTST"]

# Build MODEL_REGISTRY by taking available models from the desired lists in order
MODEL_REGISTRY = []
for name in (DESIRED_SIMPLE + DESIRED_ADVANCED):
	if name in discovered:
		MODEL_REGISTRY.append(name)

print("Using MODEL_REGISTRY (simple first, then advanced):", MODEL_REGISTRY)

# Where to save benchmark results
RESULTS_DIR = Path("results")
RESULTS_DIR.mkdir(exist_ok=True)

Discovered model modules: ['Autoformer', 'DLinear', 'FITS', 'FiLM', 'FreTS', 'HI', 'Informer', 'Koopa', 'Leddam', 'LightTS', 'MTSMixer', 'NLinear', 'NonstationaryTransformer', 'PatchTST', 'SOFTS', 'STID', 'SegRNN', 'SparseTSF', 'StemGNN', 'TiDE', 'TimeKAN', 'TimeMixer', 'TimeXer', 'Timer', 'TimesNet', 'iTransformer']

In [ ]:
# Benchmark runner: imports model classes/configs, trains and evaluates, and collects metrics.
import os
from pathlib import Path
from glob import glob

def find_attr_case(module, candidates):
	for name in candidates:
		if hasattr(module, name):
			return getattr(module, name)
	return None

available_models = []
failed_models = []
results = []

for model_name in MODEL_REGISTRY:
	try:
		mod = importlib.import_module(f"basicts.models.{model_name}")
	except Exception as e:
		failed_models.append({"model": model_name, "error": f"import error: {e}"})
		continue

	# Heuristics to find a forecasting wrapper or a model class
	# Prefer classes mentioning 'Forecast' in their name, else fallback to class named like model_name
	model_cls = None
	for attr in dir(mod):
		if "Forecast" in attr:
			model_cls = getattr(mod, attr)
			break
	if model_cls is None and hasattr(mod, model_name):
		model_cls = getattr(mod, model_name)

	# Find a config dataclass
	config_cls = None
	if hasattr(mod, f"{model_name}Config"):
		config_cls = getattr(mod, f"{model_name}Config")
	else:
		# fallback: any attribute that endswith Config
		for attr in dir(mod):
			if attr.endswith("Config"):
				config_cls = getattr(mod, attr)
				break

	if model_cls is None or config_cls is None:
		failed_models.append({"model": model_name, "error": "missing model class or config in module"})
		continue

	print(f"Benchmarking {model_name}...")

	# instantiate model config with shared required fields; configs have defaults for optional args
	try:
		# Some config classes accept num_features, some don't; pass what is common
		model_config = config_cls(input_len=INPUT_LEN, output_len=OUTPUT_LEN, num_features=NUM_FEATURES)
	except TypeError:
		# fallback without num_features
		model_config = config_cls(input_len=INPUT_LEN, output_len=OUTPUT_LEN)

	ckpt_dir = Path(f"checkpoints/benchmark/{model_name}/{DATASET_NAME}_{INPUT_LEN}_{OUTPUT_LEN}")

	cfg = BasicTSForecastingConfig(
		model=model_cls,
		model_config=model_config,
		taskflow=BasicTSForecastingTaskFlow(),
		ckpt_save_dir=str(ckpt_dir),
		**SHARED_CONFIG,
	)

	# Train and evaluate, catching any errors so the loop continues
	try:
		BasicTSLauncher.launch_training(cfg)
	except Exception as e:
		tb = traceback.format_exc()
		failed_models.append({"model": model_name, "error": f"train error: {e}\n{tb}"})
		continue

	try:
		# Passing None lets the runner pick the best checkpoint according to target metric
		BasicTSLauncher.launch_evaluation(cfg, None)
	except Exception as e:
		tb = traceback.format_exc()
		failed_models.append({"model": model_name, "error": f"eval error: {e}\n{tb}"})
		# still try to find any saved metrics

	# Find the most recent test_metrics.json under the ckpt_dir tree
	metrics_files = list(Path(ckpt_dir).rglob("test_metrics.json"))
	if not metrics_files:
		# no metrics saved
		failed_models.append({"model": model_name, "error": "no test_metrics.json found after eval"})
		continue

	metrics_file = max(metrics_files, key=lambda p: p.stat().st_mtime)
	try:
		with open(metrics_file, "r") as f:
			metrics = json.load(f)
	except Exception as e:
		failed_models.append({"model": model_name, "error": f"failed reading metrics: {e}"})
		continue

	overall = metrics.get("overall", {})

	# Normalize / compute missing metrics
	mae = overall.get("MAE")
	mse = overall.get("MSE")
	rmse = overall.get("RMSE") if overall.get("RMSE") is not None else (sqrt(mse) if mse is not None else None)
	mape = overall.get("MAPE")
	wape = overall.get("WAPE")

	results.append({
		"model": model_name,
		"MAE": mae,
		"MSE": mse,
		"RMSE": rmse,
		"MAPE": mape,
		"WAPE": wape,
		"metrics_file": str(metrics_file),
		"ckpt_dir": str(ckpt_dir),
	})

# Save results
df = pd.DataFrame(results)
if not df.empty:
	df_sorted = df.sort_values(by=["MAE", "MSE"], na_position="last")
	df_sorted.to_csv(RESULTS_DIR / "model_benchmark_results.csv", index=False)
	df_sorted.to_json(RESULTS_DIR / "model_benchmark_results.json", orient="records", indent=2)

# Save failed models
fm_df = pd.DataFrame(failed_models)
if not fm_df.empty:
	fm_df.to_csv(RESULTS_DIR / "model_benchmark_failed.csv", index=False)

print("Benchmark finished. Results saved to results/")

2026-06-16 09:22:49,283 - BasicTS-launcher - INFO - Launching BasicTS training.
2026-06-16 09:22:49,296 - BasicTS - INFO - Building model.
2026-06-16 09:22:49,300 - BasicTS - INFO - Set ckpt save dir: "checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888"
2026-06-16 09:22:49,302 - BasicTS-training - INFO - Initializing training.
2026-06-16 09:22:49,302 - BasicTS-training - INFO - Building train data loader.

Benchmarking DLinear...

2026-06-16 09:22:51,138 - BasicTS-training - INFO - Set optim: Adam
2026-06-16 09:22:51,139 - BasicTS-training - INFO - Building val data loader.
2026-06-16 09:22:51,147 - BasicTS-training - INFO - Building test data loader.
2026-06-16 09:22:51,149 - BasicTS-training - INFO - Total parameters: 2328
2026-06-16 09:22:51,150 - BasicTS-training - INFO - Trainable parameters: 2328
2026-06-16 09:22:51,150 - BasicTS-training - INFO - Epoch 1 / 5
100%|██████████| 267/267 [00:00<00:00, 279.85it/s]
2026-06-16 09:22:52,111 - BasicTS-training - INFO - Result <train>: [train/time: 0.96 (s), train/loss: 0.3860, train/MAE: 0.3860, train/MSE: 0.3241, train/RMSE: 0.5693, train/MAPE: 5.0397, train/WAPE: 0.7198]
2026-06-16 09:22:52,114 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 489.99it/s]
2026-06-16 09:22:52,295 - BasicTS-training - INFO - Result <val>: [val/time: 0.18 (s), val/loss: 0.3935, val/MAE: 0.3935, val/MSE: 0.3471, val/RMSE: 0.5891, val/MAPE: 5.3301, val/WAPE: 0.6253]
2026-06-16 09:22:52,304 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\DLinear_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 490.23it/s]
2026-06-16 09:22:52,484 - BasicTS-training - INFO - Result <test>: [test/time: 0.18 (s), test/loss: 0.3442, test/MAE: 0.3442, test/MSE: 0.2921, test/RMSE: 0.5405, test/MAPE: 8.3238, test/WAPE: 0.5668]
2026-06-16 09:22:52,490 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\DLinear_1.pt saved
2026-06-16 09:22:52,490 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:22:57
2026-06-16 09:22:52,491 - BasicTS-training - INFO - Epoch 2 / 5
100%|██████████| 267/267 [00:00<00:00, 316.61it/s]
2026-06-16 09:22:53,338 - BasicTS-training - INFO - Result <train>: [train/time: 0.85 (s), train/loss: 0.3322, train/MAE: 0.3322, train/MSE: 0.2458, train/RMSE: 0.4958, train/MAPE: 4.5717, train/WAPE: 0.6298]
2026-06-16 09:22:53,341 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 525.02it/s]
2026-06-16 09:22:53,508 - BasicTS-training - INFO - Result <val>: [val/time: 0.17 (s), val/loss: 0.3807, val/MAE: 0.3807, val/MSE: 0.3349, val/RMSE: 0.5787, val/MAPE: 5.4499, val/WAPE: 0.6194]
2026-06-16 09:22:53,513 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\DLinear_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 505.72it/s]
2026-06-16 09:22:53,689 - BasicTS-training - INFO - Result <test>: [test/time: 0.17 (s), test/loss: 0.3350, test/MAE: 0.3350, test/MSE: 0.2860, test/RMSE: 0.5348, test/MAPE: 8.4864, test/WAPE: 0.5621]
2026-06-16 09:22:53,694 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\DLinear_2.pt saved
2026-06-16 09:22:53,695 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:22:57
2026-06-16 09:22:53,695 - BasicTS-training - INFO - Epoch 3 / 5
100%|██████████| 267/267 [00:00<00:00, 327.39it/s]
2026-06-16 09:22:54,514 - BasicTS-training - INFO - Result <train>: [train/time: 0.82 (s), train/loss: 0.3283, train/MAE: 0.3283, train/MSE: 0.2429, train/RMSE: 0.4929, train/MAPE: 4.5462, train/WAPE: 0.6234]
2026-06-16 09:22:54,517 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 552.21it/s]
2026-06-16 09:22:54,676 - BasicTS-training - INFO - Result <val>: [val/time: 0.16 (s), val/loss: 0.3818, val/MAE: 0.3818, val/MSE: 0.3361, val/RMSE: 0.5798, val/MAPE: 5.4063, val/WAPE: 0.6206]
100%|██████████| 87/87 [00:00<00:00, 486.06it/s]
2026-06-16 09:22:54,862 - BasicTS-training - INFO - Result <test>: [test/time: 0.18 (s), test/loss: 0.3326, test/MAE: 0.3326, test/MSE: 0.2832, test/RMSE: 0.5322, test/MAPE: 8.2285, test/WAPE: 0.5562]
2026-06-16 09:22:54,867 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\DLinear_3.pt saved
2026-06-16 09:22:54,868 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:22:57
2026-06-16 09:22:54,869 - BasicTS-training - INFO - Epoch 4 / 5
100%|██████████| 267/267 [00:00<00:00, 322.77it/s]
2026-06-16 09:22:55,698 - BasicTS-training - INFO - Result <train>: [train/time: 0.83 (s), train/loss: 0.3273, train/MAE: 0.3273, train/MSE: 0.2419, train/RMSE: 0.4919, train/MAPE: 4.5178, train/WAPE: 0.6210]
2026-06-16 09:22:55,701 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 510.53it/s]
2026-06-16 09:22:55,874 - BasicTS-training - INFO - Result <val>: [val/time: 0.17 (s), val/loss: 0.3800, val/MAE: 0.3800, val/MSE: 0.3356, val/RMSE: 0.5793, val/MAPE: 5.4274, val/WAPE: 0.6206]
2026-06-16 09:22:55,878 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\DLinear_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 466.00it/s]
2026-06-16 09:22:56,067 - BasicTS-training - INFO - Result <test>: [test/time: 0.19 (s), test/loss: 0.3313, test/MAE: 0.3313, test/MSE: 0.2827, test/RMSE: 0.5317, test/MAPE: 8.3728, test/WAPE: 0.5573]
2026-06-16 09:22:56,073 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\DLinear_4.pt saved
2026-06-16 09:22:56,074 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:22:57
2026-06-16 09:22:56,075 - BasicTS-training - INFO - Epoch 5 / 5
100%|█████████▉| 266/267 [00:00<00:00, 329.27it/s]
2026-06-16 09:22:56,884 - BasicTS-training - INFO - Result <train>: [train/time: 0.81 (s), train/loss: 0.3268, train/MAE: 0.3268, train/MSE: 0.2416, train/RMSE: 0.4915, train/MAPE: 4.5107, train/WAPE: 0.6203]
2026-06-16 09:22:56,887 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 511.28it/s]
2026-06-16 09:22:57,059 - BasicTS-training - INFO - Result <val>: [val/time: 0.17 (s), val/loss: 0.3809, val/MAE: 0.3809, val/MSE: 0.3377, val/RMSE: 0.5811, val/MAPE: 5.4335, val/WAPE: 0.6222]
100%|██████████| 87/87 [00:00<00:00, 499.72it/s]
2026-06-16 09:22:57,237 - BasicTS-training - INFO - Result <test>: [test/time: 0.18 (s), test/loss: 0.3305, test/MAE: 0.3305, test/MSE: 0.2823, test/RMSE: 0.5313, test/MAPE: 8.4660, test/WAPE: 0.5562]
2026-06-16 09:22:57,243 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\DLinear_5.pt saved
2026-06-16 09:22:57,246 - BasicTS-training - INFO - The training finished at 2026-06-16 09:22:57
2026-06-16 09:22:57,247 - BasicTS-training - INFO - Evaluating the best model on the test set.
2026-06-16 09:22:57,248 - BasicTS-training - INFO - Loading Checkpoint from 'checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\DLinear_best_val_MAE.pt'
100%|██████████| 87/87 [00:00<00:00, 365.06it/s]
2026-06-16 09:22:57,507 - BasicTS-training - INFO - Result <test>: [test/time: 0.24 (s), test/loss: 0.3313, test/MAE: 0.3313, test/MSE: 0.2827, test/RMSE: 0.5317, test/MAPE: 8.3728, test/WAPE: 0.5573]
2026-06-16 09:22:57,508 - BasicTS-training - INFO - Test results saved to checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\test_results.
2026-06-16 09:22:57,509 - BasicTS-training - INFO - Test metrics saved to checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\test_metrics.json.
2026-06-16 09:22:57,511 - BasicTS-launcher - INFO - Launching BasicTS evaluation.
2026-06-16 09:22:57,515 - BasicTS - INFO - Building model.
2026-06-16 09:22:57,516 - BasicTS - INFO - Set ckpt save dir: "checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888"
2026-06-16 09:22:57,518 - BasicTS-evaluation - INFO - Loading Checkpoint from 'checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\DLinear_best_val_MAE.pt'
2026-06-16 09:22:57,521 - BasicTS-evaluation - INFO - Building test data loader.
100%|██████████| 87/87 [00:00<00:00, 416.09it/s]
2026-06-16 09:22:57,733 - BasicTS-evaluation - INFO - Result <test>: [test/time: 0.21 (s), test/loss: 0.3313, test/MAE: 0.3313, test/MSE: 0.2827, test/RMSE: 0.5317, test/MAPE: 8.3728, test/WAPE: 0.5573]
2026-06-16 09:22:57,734 - BasicTS-evaluation - INFO - Test results saved to checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\test_results.
2026-06-16 09:22:57,735 - BasicTS-evaluation - INFO - Test metrics saved to checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a36e17a575e4f938c2d8d175d2888\test_metrics.json.
2026-06-16 09:22:57,746 - BasicTS-launcher - INFO - Launching BasicTS training.
2026-06-16 09:22:57,752 - BasicTS - INFO - Building model.
2026-06-16 09:22:57,753 - BasicTS - INFO - Set ckpt save dir: "checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3"
2026-06-16 09:22:57,754 - BasicTS-training - INFO - Initializing training.
2026-06-16 09:22:57,754 - BasicTS-training - INFO - Building train data loader.
2026-06-16 09:22:57,758 - BasicTS-training - INFO - Set optim: Adam
2026-06-16 09:22:57,759 - BasicTS-training - INFO - Building val data loader.
2026-06-16 09:22:57,760 - BasicTS-training - INFO - Building test data loader.
2026-06-16 09:22:57,761 - BasicTS-training - INFO - Total parameters: 1164
2026-06-16 09:22:57,761 - BasicTS-training - INFO - Trainable parameters: 1164
2026-06-16 09:22:57,762 - BasicTS-training - INFO - Epoch 1 / 5

Benchmarking NLinear...

100%|██████████| 267/267 [00:00<00:00, 418.38it/s]
2026-06-16 09:22:58,402 - BasicTS-training - INFO - Result <train>: [train/time: 0.64 (s), train/loss: 0.3831, train/MAE: 0.3831, train/MSE: 0.3176, train/RMSE: 0.5636, train/MAPE: 5.3838, train/WAPE: 0.7289]
2026-06-16 09:22:58,405 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 689.03it/s]
2026-06-16 09:22:58,534 - BasicTS-training - INFO - Result <val>: [val/time: 0.13 (s), val/loss: 0.3935, val/MAE: 0.3935, val/MSE: 0.3524, val/RMSE: 0.5936, val/MAPE: 5.8268, val/WAPE: 0.6467]
2026-06-16 09:22:58,538 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\NLinear_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 697.79it/s]
2026-06-16 09:22:58,665 - BasicTS-training - INFO - Result <test>: [test/time: 0.13 (s), test/loss: 0.3491, test/MAE: 0.3491, test/MSE: 0.2999, test/RMSE: 0.5477, test/MAPE: 8.8855, test/WAPE: 0.5888]
2026-06-16 09:22:58,670 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\NLinear_1.pt saved
2026-06-16 09:22:58,670 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:02
2026-06-16 09:22:58,670 - BasicTS-training - INFO - Epoch 2 / 5
100%|██████████| 267/267 [00:00<00:00, 442.07it/s]
2026-06-16 09:22:59,277 - BasicTS-training - INFO - Result <train>: [train/time: 0.61 (s), train/loss: 0.3364, train/MAE: 0.3364, train/MSE: 0.2519, train/RMSE: 0.5019, train/MAPE: 4.7427, train/WAPE: 0.6432]
2026-06-16 09:22:59,280 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 693.08it/s]
2026-06-16 09:22:59,407 - BasicTS-training - INFO - Result <val>: [val/time: 0.13 (s), val/loss: 0.3847, val/MAE: 0.3847, val/MSE: 0.3411, val/RMSE: 0.5840, val/MAPE: 5.6954, val/WAPE: 0.6313]
2026-06-16 09:22:59,412 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\NLinear_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 684.66it/s]
2026-06-16 09:22:59,542 - BasicTS-training - INFO - Result <test>: [test/time: 0.13 (s), test/loss: 0.3389, test/MAE: 0.3389, test/MSE: 0.2904, test/RMSE: 0.5389, test/MAPE: 8.8810, test/WAPE: 0.5718]
2026-06-16 09:22:59,548 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\NLinear_2.pt saved
2026-06-16 09:22:59,550 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:02
2026-06-16 09:22:59,550 - BasicTS-training - INFO - Epoch 3 / 5
100%|██████████| 267/267 [00:00<00:00, 423.44it/s]
2026-06-16 09:23:00,183 - BasicTS-training - INFO - Result <train>: [train/time: 0.63 (s), train/loss: 0.3308, train/MAE: 0.3308, train/MSE: 0.2460, train/RMSE: 0.4960, train/MAPE: 4.6712, train/WAPE: 0.6328]
2026-06-16 09:23:00,186 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 722.99it/s]
2026-06-16 09:23:00,308 - BasicTS-training - INFO - Result <val>: [val/time: 0.12 (s), val/loss: 0.3815, val/MAE: 0.3815, val/MSE: 0.3360, val/RMSE: 0.5796, val/MAPE: 5.6874, val/WAPE: 0.6254]
2026-06-16 09:23:00,312 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\NLinear_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 732.66it/s]
2026-06-16 09:23:00,434 - BasicTS-training - INFO - Result <test>: [test/time: 0.12 (s), test/loss: 0.3383, test/MAE: 0.3383, test/MSE: 0.2912, test/RMSE: 0.5396, test/MAPE: 8.9054, test/WAPE: 0.5706]
2026-06-16 09:23:00,438 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\NLinear_3.pt saved
2026-06-16 09:23:00,439 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:02
2026-06-16 09:23:00,440 - BasicTS-training - INFO - Epoch 4 / 5
100%|██████████| 267/267 [00:00<00:00, 446.53it/s]
2026-06-16 09:23:01,040 - BasicTS-training - INFO - Result <train>: [train/time: 0.60 (s), train/loss: 0.3284, train/MAE: 0.3284, train/MSE: 0.2438, train/RMSE: 0.4937, train/MAPE: 4.6343, train/WAPE: 0.6279]
2026-06-16 09:23:01,043 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 678.41it/s]
2026-06-16 09:23:01,173 - BasicTS-training - INFO - Result <val>: [val/time: 0.13 (s), val/loss: 0.3821, val/MAE: 0.3821, val/MSE: 0.3423, val/RMSE: 0.5850, val/MAPE: 5.5516, val/WAPE: 0.6293]
100%|██████████| 87/87 [00:00<00:00, 745.27it/s]
2026-06-16 09:23:01,296 - BasicTS-training - INFO - Result <test>: [test/time: 0.12 (s), test/loss: 0.3322, test/MAE: 0.3322, test/MSE: 0.2852, test/RMSE: 0.5340, test/MAPE: 8.4957, test/WAPE: 0.5633]
2026-06-16 09:23:01,303 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\NLinear_4.pt saved
2026-06-16 09:23:01,304 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:02
2026-06-16 09:23:01,304 - BasicTS-training - INFO - Epoch 5 / 5
100%|█████████▉| 266/267 [00:00<00:00, 407.92it/s]
2026-06-16 09:23:01,959 - BasicTS-training - INFO - Result <train>: [train/time: 0.65 (s), train/loss: 0.3277, train/MAE: 0.3277, train/MSE: 0.2432, train/RMSE: 0.4931, train/MAPE: 4.6023, train/WAPE: 0.6264]
2026-06-16 09:23:01,961 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 671.77it/s]
2026-06-16 09:23:02,093 - BasicTS-training - INFO - Result <val>: [val/time: 0.13 (s), val/loss: 0.3798, val/MAE: 0.3798, val/MSE: 0.3339, val/RMSE: 0.5778, val/MAPE: 5.6137, val/WAPE: 0.6224]
2026-06-16 09:23:02,097 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\NLinear_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 646.38it/s]
2026-06-16 09:23:02,235 - BasicTS-training - INFO - Result <test>: [test/time: 0.14 (s), test/loss: 0.3359, test/MAE: 0.3359, test/MSE: 0.2891, test/RMSE: 0.5376, test/MAPE: 8.9596, test/WAPE: 0.5683]
2026-06-16 09:23:02,240 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\NLinear_5.pt saved
2026-06-16 09:23:02,242 - BasicTS-training - INFO - The training finished at 2026-06-16 09:23:02
2026-06-16 09:23:02,243 - BasicTS-training - INFO - Evaluating the best model on the test set.
2026-06-16 09:23:02,244 - BasicTS-training - INFO - Loading Checkpoint from 'checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\NLinear_best_val_MAE.pt'
100%|██████████| 87/87 [00:00<00:00, 474.88it/s]
2026-06-16 09:23:02,441 - BasicTS-training - INFO - Result <test>: [test/time: 0.19 (s), test/loss: 0.3359, test/MAE: 0.3359, test/MSE: 0.2891, test/RMSE: 0.5376, test/MAPE: 8.9596, test/WAPE: 0.5683]
2026-06-16 09:23:02,441 - BasicTS-training - INFO - Test results saved to checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\test_results.
2026-06-16 09:23:02,443 - BasicTS-training - INFO - Test metrics saved to checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\test_metrics.json.
2026-06-16 09:23:02,445 - BasicTS-launcher - INFO - Launching BasicTS evaluation.
2026-06-16 09:23:02,448 - BasicTS - INFO - Building model.
2026-06-16 09:23:02,449 - BasicTS - INFO - Set ckpt save dir: "checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3"
2026-06-16 09:23:02,451 - BasicTS-evaluation - INFO - Loading Checkpoint from 'checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\NLinear_best_val_MAE.pt'
2026-06-16 09:23:02,453 - BasicTS-evaluation - INFO - Building test data loader.
100%|██████████| 87/87 [00:00<00:00, 490.23it/s]
2026-06-16 09:23:02,635 - BasicTS-evaluation - INFO - Result <test>: [test/time: 0.18 (s), test/loss: 0.3359, test/MAE: 0.3359, test/MSE: 0.2891, test/RMSE: 0.5376, test/MAPE: 8.9596, test/WAPE: 0.5683]
2026-06-16 09:23:02,635 - BasicTS-evaluation - INFO - Test results saved to checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\test_results.
2026-06-16 09:23:02,637 - BasicTS-evaluation - INFO - Test metrics saved to checkpoints\benchmark\NLinear\ETTh1_96_12\5484d362080ec2be957991908b835bf3\test_metrics.json.
2026-06-16 09:23:02,652 - BasicTS-launcher - INFO - Launching BasicTS training.
2026-06-16 09:23:02,658 - BasicTS - INFO - Building model.
2026-06-16 09:23:02,662 - BasicTS - INFO - Set ckpt save dir: "checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b"
2026-06-16 09:23:02,663 - BasicTS-training - INFO - Initializing training.
2026-06-16 09:23:02,664 - BasicTS-training - INFO - Building train data loader.
2026-06-16 09:23:02,669 - BasicTS-training - INFO - Set optim: Adam
2026-06-16 09:23:02,669 - BasicTS-training - INFO - Building val data loader.
2026-06-16 09:23:02,671 - BasicTS-training - INFO - Building test data loader.
2026-06-16 09:23:02,672 - BasicTS-training - INFO - Total parameters: 199044
2026-06-16 09:23:02,672 - BasicTS-training - INFO - Trainable parameters: 199044
2026-06-16 09:23:02,673 - BasicTS-training - INFO - Epoch 1 / 5

Benchmarking MTSMixer...

100%|██████████| 267/267 [00:03<00:00, 76.54it/s]
2026-06-16 09:23:06,164 - BasicTS-training - INFO - Result <train>: [train/time: 3.49 (s), train/loss: 0.3907, train/MAE: 0.3907, train/MSE: 0.3208, train/RMSE: 0.5664, train/MAPE: 5.3749, train/WAPE: 0.7403]
2026-06-16 09:23:06,168 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 239.63it/s]
2026-06-16 09:23:06,533 - BasicTS-training - INFO - Result <val>: [val/time: 0.36 (s), val/loss: 0.4674, val/MAE: 0.4674, val/MSE: 0.4612, val/RMSE: 0.6791, val/MAPE: 6.3007, val/WAPE: 0.7668]
2026-06-16 09:23:06,542 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\MTSMixer_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 236.61it/s]
2026-06-16 09:23:06,913 - BasicTS-training - INFO - Result <test>: [test/time: 0.37 (s), test/loss: 0.3901, test/MAE: 0.3901, test/MSE: 0.3476, test/RMSE: 0.5896, test/MAPE: 10.1038, test/WAPE: 0.6487]
2026-06-16 09:23:06,920 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\MTSMixer_1.pt saved
2026-06-16 09:23:06,921 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:23
2026-06-16 09:23:06,922 - BasicTS-training - INFO - Epoch 2 / 5
100%|██████████| 267/267 [00:03<00:00, 84.84it/s]
2026-06-16 09:23:10,071 - BasicTS-training - INFO - Result <train>: [train/time: 3.15 (s), train/loss: 0.3718, train/MAE: 0.3718, train/MSE: 0.2945, train/RMSE: 0.5427, train/MAPE: 5.1494, train/WAPE: 0.7055]
2026-06-16 09:23:10,074 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 252.75it/s]
2026-06-16 09:23:10,420 - BasicTS-training - INFO - Result <val>: [val/time: 0.35 (s), val/loss: 0.4602, val/MAE: 0.4602, val/MSE: 0.4483, val/RMSE: 0.6695, val/MAPE: 6.1938, val/WAPE: 0.7483]
2026-06-16 09:23:10,428 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\MTSMixer_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 247.17it/s]
2026-06-16 09:23:10,782 - BasicTS-training - INFO - Result <test>: [test/time: 0.35 (s), test/loss: 0.3812, test/MAE: 0.3812, test/MSE: 0.3435, test/RMSE: 0.5861, test/MAPE: 9.7438, test/WAPE: 0.6216]
2026-06-16 09:23:10,789 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\MTSMixer_2.pt saved
2026-06-16 09:23:10,790 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:22
2026-06-16 09:23:10,790 - BasicTS-training - INFO - Epoch 3 / 5
100%|██████████| 267/267 [00:03<00:00, 84.47it/s]
2026-06-16 09:23:13,953 - BasicTS-training - INFO - Result <train>: [train/time: 3.16 (s), train/loss: 0.3642, train/MAE: 0.3642, train/MSE: 0.2840, train/RMSE: 0.5329, train/MAPE: 5.0212, train/WAPE: 0.6928]
2026-06-16 09:23:13,956 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 221.29it/s]
2026-06-16 09:23:14,353 - BasicTS-training - INFO - Result <val>: [val/time: 0.40 (s), val/loss: 0.4723, val/MAE: 0.4723, val/MSE: 0.4765, val/RMSE: 0.6903, val/MAPE: 6.1524, val/WAPE: 0.7570]
100%|██████████| 87/87 [00:00<00:00, 254.88it/s]
2026-06-16 09:23:14,699 - BasicTS-training - INFO - Result <test>: [test/time: 0.34 (s), test/loss: 0.3801, test/MAE: 0.3801, test/MSE: 0.3497, test/RMSE: 0.5913, test/MAPE: 9.2649, test/WAPE: 0.6130]
2026-06-16 09:23:14,708 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\MTSMixer_3.pt saved
2026-06-16 09:23:14,709 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:22
2026-06-16 09:23:14,710 - BasicTS-training - INFO - Epoch 4 / 5
100%|██████████| 267/267 [00:03<00:00, 86.57it/s]
2026-06-16 09:23:17,795 - BasicTS-training - INFO - Result <train>: [train/time: 3.09 (s), train/loss: 0.3574, train/MAE: 0.3574, train/MSE: 0.2725, train/RMSE: 0.5220, train/MAPE: 4.9627, train/WAPE: 0.6821]
2026-06-16 09:23:17,798 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 249.37it/s]
2026-06-16 09:23:18,150 - BasicTS-training - INFO - Result <val>: [val/time: 0.35 (s), val/loss: 0.4539, val/MAE: 0.4539, val/MSE: 0.4300, val/RMSE: 0.6557, val/MAPE: 5.8431, val/WAPE: 0.7357]
2026-06-16 09:23:18,157 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\MTSMixer_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 249.56it/s]
2026-06-16 09:23:18,509 - BasicTS-training - INFO - Result <test>: [test/time: 0.35 (s), test/loss: 0.3741, test/MAE: 0.3741, test/MSE: 0.3314, test/RMSE: 0.5757, test/MAPE: 9.9435, test/WAPE: 0.6145]
2026-06-16 09:23:18,517 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\MTSMixer_4.pt saved
2026-06-16 09:23:18,517 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:22
2026-06-16 09:23:18,518 - BasicTS-training - INFO - Epoch 5 / 5
100%|█████████▉| 266/267 [00:03<00:00, 79.04it/s]
2026-06-16 09:23:21,885 - BasicTS-training - INFO - Result <train>: [train/time: 3.37 (s), train/loss: 0.3510, train/MAE: 0.3510, train/MSE: 0.2614, train/RMSE: 0.5112, train/MAPE: 4.8952, train/WAPE: 0.6717]
2026-06-16 09:23:21,888 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 200.82it/s]
2026-06-16 09:23:22,326 - BasicTS-training - INFO - Result <val>: [val/time: 0.44 (s), val/loss: 0.4486, val/MAE: 0.4486, val/MSE: 0.4272, val/RMSE: 0.6536, val/MAPE: 5.9030, val/WAPE: 0.7433]
2026-06-16 09:23:22,337 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\MTSMixer_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 234.06it/s]
2026-06-16 09:23:22,712 - BasicTS-training - INFO - Result <test>: [test/time: 0.37 (s), test/loss: 0.3666, test/MAE: 0.3666, test/MSE: 0.3258, test/RMSE: 0.5708, test/MAPE: 9.8142, test/WAPE: 0.6056]
2026-06-16 09:23:22,722 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\MTSMixer_5.pt saved
2026-06-16 09:23:22,727 - BasicTS-training - INFO - The training finished at 2026-06-16 09:23:22
2026-06-16 09:23:22,728 - BasicTS-training - INFO - Evaluating the best model on the test set.
2026-06-16 09:23:22,728 - BasicTS-training - INFO - Loading Checkpoint from 'checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\MTSMixer_best_val_MAE.pt'
100%|██████████| 87/87 [00:00<00:00, 195.31it/s]
2026-06-16 09:23:23,191 - BasicTS-training - INFO - Result <test>: [test/time: 0.45 (s), test/loss: 0.3666, test/MAE: 0.3666, test/MSE: 0.3258, test/RMSE: 0.5708, test/MAPE: 9.8142, test/WAPE: 0.6056]
2026-06-16 09:23:23,192 - BasicTS-training - INFO - Test results saved to checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\test_results.
2026-06-16 09:23:23,193 - BasicTS-training - INFO - Test metrics saved to checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\test_metrics.json.
2026-06-16 09:23:23,195 - BasicTS-launcher - INFO - Launching BasicTS evaluation.
2026-06-16 09:23:23,196 - BasicTS - INFO - Building model.
2026-06-16 09:23:23,199 - BasicTS - INFO - Set ckpt save dir: "checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b"
2026-06-16 09:23:23,200 - BasicTS-evaluation - INFO - Loading Checkpoint from 'checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\MTSMixer_best_val_MAE.pt'
2026-06-16 09:23:23,207 - BasicTS-evaluation - INFO - Building test data loader.
100%|██████████| 87/87 [00:00<00:00, 199.59it/s]
2026-06-16 09:23:23,647 - BasicTS-evaluation - INFO - Result <test>: [test/time: 0.44 (s), test/loss: 0.3666, test/MAE: 0.3666, test/MSE: 0.3258, test/RMSE: 0.5708, test/MAPE: 9.8142, test/WAPE: 0.6056]
2026-06-16 09:23:23,648 - BasicTS-evaluation - INFO - Test results saved to checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\test_results.
2026-06-16 09:23:23,649 - BasicTS-evaluation - INFO - Test metrics saved to checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a58d8709da31bf66f2908b1584cb9b\test_metrics.json.
2026-06-16 09:23:23,662 - BasicTS-launcher - INFO - Launching BasicTS training.
2026-06-16 09:23:23,669 - BasicTS - INFO - Building model.
2026-06-16 09:23:23,800 - BasicTS - INFO - Set ckpt save dir: "checkpoints\benchmark\TimesNet\ETTh1_96_12\c5d3400e262b3928dd0983a211527c3f"
2026-06-16 09:23:23,801 - BasicTS-training - INFO - Initializing training.
2026-06-16 09:23:23,802 - BasicTS-training - INFO - Building train data loader.
2026-06-16 09:23:23,806 - BasicTS-training - INFO - Set optim: Adam
2026-06-16 09:23:23,807 - BasicTS-training - INFO - Building val data loader.
2026-06-16 09:23:23,808 - BasicTS-training - INFO - Building test data loader.
2026-06-16 09:23:23,809 - BasicTS-training - INFO - Total parameters: 18372083
2026-06-16 09:23:23,810 - BasicTS-training - INFO - Trainable parameters: 18372083
2026-06-16 09:23:23,811 - BasicTS-training - INFO - Epoch 1 / 5

Benchmarking TimesNet...

  0%|          | 0/267 [00:00<?, ?it/s]
2026-06-16 09:23:23,816 - BasicTS-training - ERROR - Traceback (most recent call last):
  File "C:\Users\luwil\OneDrive\Documents\Code\BasicTS\src\basicts\launcher.py", line 109, in training_func
    runner.train()
  File "C:\Users\luwil\OneDrive\Documents\Code\BasicTS\src\basicts\runners\basicts_runner.py", line 306, in train
    self._train_loop()
  File "C:\Users\luwil\OneDrive\Documents\Code\BasicTS\src\basicts\runners\basicts_runner.py", line 451, in _train_loop
    forward_return = self._forward(self.model, data, self.global_steps, self.epoch)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luwil\OneDrive\Documents\Code\BasicTS\src\basicts\runners\basicts_runner.py", line 787, in _forward
    forward_return = model(inputs, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\luwil\miniconda3\envs\BasicTS\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\luwil\miniconda3\envs\BasicTS\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TimesNetForForecasting.forward() missing 1 required positional argument: 'inputs_timestamps'

2026-06-16 09:23:23,826 - BasicTS-launcher - INFO - Launching BasicTS training.
2026-06-16 09:23:23,831 - BasicTS - INFO - Building model.
2026-06-16 09:23:23,837 - BasicTS - INFO - Set ckpt save dir: "checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd"

Benchmarking iTransformer...

2026-06-16 09:23:23,838 - BasicTS-training - INFO - Initializing training.
2026-06-16 09:23:23,839 - BasicTS-training - INFO - Building train data loader.
2026-06-16 09:23:23,842 - BasicTS-training - INFO - Set optim: Adam
2026-06-16 09:23:23,843 - BasicTS-training - INFO - Building val data loader.
2026-06-16 09:23:23,844 - BasicTS-training - INFO - Building test data loader.
2026-06-16 09:23:23,846 - BasicTS-training - INFO - Total parameters: 818188
2026-06-16 09:23:23,846 - BasicTS-training - INFO - Trainable parameters: 818188
2026-06-16 09:23:23,847 - BasicTS-training - INFO - Epoch 1 / 5
100%|██████████| 267/267 [00:05<00:00, 52.65it/s]
2026-06-16 09:23:28,923 - BasicTS-training - INFO - Result <train>: [train/time: 5.07 (s), train/loss: 0.3395, train/MAE: 0.3395, train/MSE: 0.2523, train/RMSE: 0.5023, train/MAPE: 4.8815, train/WAPE: 0.6480]
2026-06-16 09:23:28,926 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 172.67it/s]
2026-06-16 09:23:29,432 - BasicTS-training - INFO - Result <val>: [val/time: 0.51 (s), val/loss: 0.3805, val/MAE: 0.3805, val/MSE: 0.3336, val/RMSE: 0.5776, val/MAPE: 5.5778, val/WAPE: 0.6278]
2026-06-16 09:23:29,448 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\iTransformerForForecasting_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 160.48it/s]
2026-06-16 09:23:29,994 - BasicTS-training - INFO - Result <test>: [test/time: 0.54 (s), test/loss: 0.3430, test/MAE: 0.3430, test/MSE: 0.2883, test/RMSE: 0.5369, test/MAPE: 8.9946, test/WAPE: 0.5813]
2026-06-16 09:23:30,010 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\iTransformerForForecasting_1.pt saved
2026-06-16 09:23:30,011 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:54
2026-06-16 09:23:30,011 - BasicTS-training - INFO - Epoch 2 / 5
100%|██████████| 267/267 [00:05<00:00, 51.40it/s]
2026-06-16 09:23:35,208 - BasicTS-training - INFO - Result <train>: [train/time: 5.20 (s), train/loss: 0.3204, train/MAE: 0.3204, train/MSE: 0.2302, train/RMSE: 0.4798, train/MAPE: 4.6777, train/WAPE: 0.6092]
2026-06-16 09:23:35,211 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 166.36it/s]
2026-06-16 09:23:35,737 - BasicTS-training - INFO - Result <val>: [val/time: 0.52 (s), val/loss: 0.3688, val/MAE: 0.3688, val/MSE: 0.3190, val/RMSE: 0.5648, val/MAPE: 5.6089, val/WAPE: 0.6096]
2026-06-16 09:23:35,753 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\iTransformerForForecasting_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 171.42it/s]
2026-06-16 09:23:36,262 - BasicTS-training - INFO - Result <test>: [test/time: 0.51 (s), test/loss: 0.3343, test/MAE: 0.3343, test/MSE: 0.2822, test/RMSE: 0.5312, test/MAPE: 8.4210, test/WAPE: 0.5647]
2026-06-16 09:23:36,278 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\iTransformerForForecasting_2.pt saved
2026-06-16 09:23:36,279 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:54
2026-06-16 09:23:36,280 - BasicTS-training - INFO - Epoch 3 / 5
100%|██████████| 267/267 [00:05<00:00, 47.19it/s]
2026-06-16 09:23:41,941 - BasicTS-training - INFO - Result <train>: [train/time: 5.66 (s), train/loss: 0.3168, train/MAE: 0.3168, train/MSE: 0.2269, train/RMSE: 0.4764, train/MAPE: 4.6115, train/WAPE: 0.6010]
2026-06-16 09:23:41,944 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 159.38it/s]
2026-06-16 09:23:42,493 - BasicTS-training - INFO - Result <val>: [val/time: 0.55 (s), val/loss: 0.3662, val/MAE: 0.3662, val/MSE: 0.3160, val/RMSE: 0.5621, val/MAPE: 5.5763, val/WAPE: 0.6069]
2026-06-16 09:23:42,507 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\iTransformerForForecasting_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 165.64it/s]
2026-06-16 09:23:43,035 - BasicTS-training - INFO - Result <test>: [test/time: 0.53 (s), test/loss: 0.3330, test/MAE: 0.3330, test/MSE: 0.2816, test/RMSE: 0.5307, test/MAPE: 8.5128, test/WAPE: 0.5663]
2026-06-16 09:23:43,048 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\iTransformerForForecasting_3.pt saved
2026-06-16 09:23:43,049 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:55
2026-06-16 09:23:43,050 - BasicTS-training - INFO - Epoch 4 / 5
100%|██████████| 267/267 [00:05<00:00, 51.17it/s]
2026-06-16 09:23:48,270 - BasicTS-training - INFO - Result <train>: [train/time: 5.22 (s), train/loss: 0.3136, train/MAE: 0.3136, train/MSE: 0.2241, train/RMSE: 0.4733, train/MAPE: 4.5977, train/WAPE: 0.5938]
2026-06-16 09:23:48,274 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 162.38it/s]
2026-06-16 09:23:48,814 - BasicTS-training - INFO - Result <val>: [val/time: 0.54 (s), val/loss: 0.3685, val/MAE: 0.3685, val/MSE: 0.3190, val/RMSE: 0.5648, val/MAPE: 5.4329, val/WAPE: 0.6023]
100%|██████████| 87/87 [00:00<00:00, 163.91it/s]
2026-06-16 09:23:49,350 - BasicTS-training - INFO - Result <test>: [test/time: 0.53 (s), test/loss: 0.3252, test/MAE: 0.3252, test/MSE: 0.2707, test/RMSE: 0.5203, test/MAPE: 8.6770, test/WAPE: 0.5489]
2026-06-16 09:23:49,363 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\iTransformerForForecasting_4.pt saved
2026-06-16 09:23:49,364 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:23:55
2026-06-16 09:23:49,365 - BasicTS-training - INFO - Epoch 5 / 5
100%|█████████▉| 266/267 [00:05<00:00, 50.77it/s]
2026-06-16 09:23:54,607 - BasicTS-training - INFO - Result <train>: [train/time: 5.24 (s), train/loss: 0.3124, train/MAE: 0.3124, train/MSE: 0.2224, train/RMSE: 0.4715, train/MAPE: 4.5799, train/WAPE: 0.5917]
2026-06-16 09:23:54,610 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:00<00:00, 174.41it/s]
2026-06-16 09:23:55,112 - BasicTS-training - INFO - Result <val>: [val/time: 0.50 (s), val/loss: 0.3647, val/MAE: 0.3647, val/MSE: 0.3172, val/RMSE: 0.5632, val/MAPE: 5.4446, val/WAPE: 0.6027]
2026-06-16 09:23:55,126 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\iTransformerForForecasting_best_val_MAE.pt saved
100%|██████████| 87/87 [00:00<00:00, 178.71it/s]
2026-06-16 09:23:55,616 - BasicTS-training - INFO - Result <test>: [test/time: 0.49 (s), test/loss: 0.3264, test/MAE: 0.3264, test/MSE: 0.2721, test/RMSE: 0.5217, test/MAPE: 8.6727, test/WAPE: 0.5548]
2026-06-16 09:23:55,632 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\iTransformerForForecasting_5.pt saved
2026-06-16 09:23:55,638 - BasicTS-training - INFO - The training finished at 2026-06-16 09:23:55
2026-06-16 09:23:55,639 - BasicTS-training - INFO - Evaluating the best model on the test set.
2026-06-16 09:23:55,639 - BasicTS-training - INFO - Loading Checkpoint from 'checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\iTransformerForForecasting_best_val_MAE.pt'
100%|██████████| 87/87 [00:00<00:00, 146.12it/s]
2026-06-16 09:23:56,256 - BasicTS-training - INFO - Result <test>: [test/time: 0.60 (s), test/loss: 0.3264, test/MAE: 0.3264, test/MSE: 0.2721, test/RMSE: 0.5217, test/MAPE: 8.6727, test/WAPE: 0.5548]
2026-06-16 09:23:56,257 - BasicTS-training - INFO - Test results saved to checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\test_results.
2026-06-16 09:23:56,259 - BasicTS-training - INFO - Test metrics saved to checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\test_metrics.json.
2026-06-16 09:23:56,260 - BasicTS-launcher - INFO - Launching BasicTS evaluation.
2026-06-16 09:23:56,263 - BasicTS - INFO - Building model.
2026-06-16 09:23:56,267 - BasicTS - INFO - Set ckpt save dir: "checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd"
2026-06-16 09:23:56,269 - BasicTS-evaluation - INFO - Loading Checkpoint from 'checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\iTransformerForForecasting_best_val_MAE.pt'
2026-06-16 09:23:56,284 - BasicTS-evaluation - INFO - Building test data loader.
100%|██████████| 87/87 [00:00<00:00, 115.30it/s]
2026-06-16 09:23:57,042 - BasicTS-evaluation - INFO - Result <test>: [test/time: 0.76 (s), test/loss: 0.3264, test/MAE: 0.3264, test/MSE: 0.2721, test/RMSE: 0.5217, test/MAPE: 8.6727, test/WAPE: 0.5548]
2026-06-16 09:23:57,043 - BasicTS-evaluation - INFO - Test results saved to checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\test_results.
2026-06-16 09:23:57,044 - BasicTS-evaluation - INFO - Test metrics saved to checkpoints\benchmark\iTransformer\ETTh1_96_12\4cf6d63a4cf41e67387c6f18f28a3ecd\test_metrics.json.
2026-06-16 09:23:57,059 - BasicTS-launcher - INFO - Launching BasicTS training.
2026-06-16 09:23:57,065 - BasicTS - INFO - Building model.
2026-06-16 09:23:57,079 - BasicTS - INFO - Set ckpt save dir: "checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3"
2026-06-16 09:23:57,080 - BasicTS-training - INFO - Initializing training.
2026-06-16 09:23:57,081 - BasicTS-training - INFO - Building train data loader.
2026-06-16 09:23:57,085 - BasicTS-training - INFO - Set optim: Adam
2026-06-16 09:23:57,086 - BasicTS-training - INFO - Building val data loader.
2026-06-16 09:23:57,087 - BasicTS-training - INFO - Building test data loader.
2026-06-16 09:23:57,089 - BasicTS-training - INFO - Total parameters: 831002
2026-06-16 09:23:57,090 - BasicTS-training - INFO - Trainable parameters: 831002
2026-06-16 09:23:57,090 - BasicTS-training - INFO - Epoch 1 / 5

Benchmarking PatchTST...

100%|██████████| 267/267 [00:14<00:00, 18.59it/s]
2026-06-16 09:24:11,457 - BasicTS-training - INFO - Result <train>: [train/time: 14.37 (s), train/loss: 0.3536, train/MAE: 0.3536, train/MSE: 0.2760, train/RMSE: 0.5254, train/MAPE: 4.9939, train/WAPE: 0.6773]
2026-06-16 09:24:11,460 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:01<00:00, 63.81it/s]
2026-06-16 09:24:12,825 - BasicTS-training - INFO - Result <val>: [val/time: 1.36 (s), val/loss: 0.3936, val/MAE: 0.3936, val/MSE: 0.3521, val/RMSE: 0.5934, val/MAPE: 5.6932, val/WAPE: 0.6409]
2026-06-16 09:24:12,844 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\PatchTSTForForecasting_best_val_MAE.pt saved
100%|██████████| 87/87 [00:01<00:00, 65.22it/s]
2026-06-16 09:24:14,182 - BasicTS-training - INFO - Result <test>: [test/time: 1.34 (s), test/loss: 0.3406, test/MAE: 0.3406, test/MSE: 0.2948, test/RMSE: 0.5430, test/MAPE: 8.9710, test/WAPE: 0.5719]
2026-06-16 09:24:14,199 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\PatchTSTForForecasting_1.pt saved
2026-06-16 09:24:14,200 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:25:22
2026-06-16 09:24:14,201 - BasicTS-training - INFO - Epoch 2 / 5
100%|██████████| 267/267 [00:14<00:00, 18.21it/s]
2026-06-16 09:24:28,868 - BasicTS-training - INFO - Result <train>: [train/time: 14.67 (s), train/loss: 0.3268, train/MAE: 0.3268, train/MSE: 0.2404, train/RMSE: 0.4903, train/MAPE: 4.6110, train/WAPE: 0.6211]
2026-06-16 09:24:28,871 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:01<00:00, 58.91it/s]
2026-06-16 09:24:30,349 - BasicTS-training - INFO - Result <val>: [val/time: 1.48 (s), val/loss: 0.4013, val/MAE: 0.4013, val/MSE: 0.3591, val/RMSE: 0.5992, val/MAPE: 5.2079, val/WAPE: 0.6345]
100%|██████████| 87/87 [00:01<00:00, 63.67it/s]
2026-06-16 09:24:31,721 - BasicTS-training - INFO - Result <test>: [test/time: 1.37 (s), test/loss: 0.3453, test/MAE: 0.3453, test/MSE: 0.2955, test/RMSE: 0.5436, test/MAPE: 9.6637, test/WAPE: 0.5753]
2026-06-16 09:24:31,740 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\PatchTSTForForecasting_2.pt saved
2026-06-16 09:24:31,740 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:25:23
2026-06-16 09:24:31,741 - BasicTS-training - INFO - Epoch 3 / 5
100%|██████████| 267/267 [00:14<00:00, 18.04it/s]
2026-06-16 09:24:46,543 - BasicTS-training - INFO - Result <train>: [train/time: 14.80 (s), train/loss: 0.3236, train/MAE: 0.3236, train/MSE: 0.2368, train/RMSE: 0.4866, train/MAPE: 4.6039, train/WAPE: 0.6150]
2026-06-16 09:24:46,546 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:01<00:00, 61.93it/s]
2026-06-16 09:24:47,954 - BasicTS-training - INFO - Result <val>: [val/time: 1.41 (s), val/loss: 0.3934, val/MAE: 0.3934, val/MSE: 0.3462, val/RMSE: 0.5884, val/MAPE: 5.5967, val/WAPE: 0.6301]
2026-06-16 09:24:47,971 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\PatchTSTForForecasting_best_val_MAE.pt saved
100%|██████████| 87/87 [00:01<00:00, 60.88it/s]
2026-06-16 09:24:49,403 - BasicTS-training - INFO - Result <test>: [test/time: 1.43 (s), test/loss: 0.3403, test/MAE: 0.3403, test/MSE: 0.2878, test/RMSE: 0.5365, test/MAPE: 8.2890, test/WAPE: 0.5611]
2026-06-16 09:24:49,420 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\PatchTSTForForecasting_3.pt saved
2026-06-16 09:24:49,421 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:25:24
2026-06-16 09:24:49,421 - BasicTS-training - INFO - Epoch 4 / 5
100%|██████████| 267/267 [00:15<00:00, 17.35it/s]
2026-06-16 09:25:04,814 - BasicTS-training - INFO - Result <train>: [train/time: 15.39 (s), train/loss: 0.3211, train/MAE: 0.3211, train/MSE: 0.2341, train/RMSE: 0.4838, train/MAPE: 4.5541, train/WAPE: 0.6103]
2026-06-16 09:25:04,817 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:01<00:00, 68.87it/s]
2026-06-16 09:25:06,081 - BasicTS-training - INFO - Result <val>: [val/time: 1.26 (s), val/loss: 0.3746, val/MAE: 0.3746, val/MSE: 0.3292, val/RMSE: 0.5737, val/MAPE: 5.5198, val/WAPE: 0.6223]
2026-06-16 09:25:06,099 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\PatchTSTForForecasting_best_val_MAE.pt saved
100%|██████████| 87/87 [00:01<00:00, 69.56it/s]
2026-06-16 09:25:07,352 - BasicTS-training - INFO - Result <test>: [test/time: 1.25 (s), test/loss: 0.3335, test/MAE: 0.3335, test/MSE: 0.2910, test/RMSE: 0.5394, test/MAPE: 8.6198, test/WAPE: 0.5681]
2026-06-16 09:25:07,370 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\PatchTSTForForecasting_4.pt saved
2026-06-16 09:25:07,370 - BasicTS-training - INFO - The estimated training finish time is 2026-06-16 09:25:24
2026-06-16 09:25:07,371 - BasicTS-training - INFO - Epoch 5 / 5
100%|█████████▉| 266/267 [00:15<00:00, 17.39it/s]
2026-06-16 09:25:22,671 - BasicTS-training - INFO - Result <train>: [train/time: 15.30 (s), train/loss: 0.3193, train/MAE: 0.3193, train/MSE: 0.2325, train/RMSE: 0.4822, train/MAPE: 4.5288, train/WAPE: 0.6053]
2026-06-16 09:25:22,675 - BasicTS-training - INFO - Start validation.
100%|██████████| 87/87 [00:01<00:00, 53.53it/s]
2026-06-16 09:25:24,303 - BasicTS-training - INFO - Result <val>: [val/time: 1.63 (s), val/loss: 0.3708, val/MAE: 0.3708, val/MSE: 0.3208, val/RMSE: 0.5664, val/MAPE: 5.3245, val/WAPE: 0.6072]
2026-06-16 09:25:24,323 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\PatchTSTForForecasting_best_val_MAE.pt saved
100%|██████████| 87/87 [00:01<00:00, 56.06it/s]
2026-06-16 09:25:25,877 - BasicTS-training - INFO - Result <test>: [test/time: 1.55 (s), test/loss: 0.3301, test/MAE: 0.3301, test/MSE: 0.2800, test/RMSE: 0.5292, test/MAPE: 9.0062, test/WAPE: 0.5611]
2026-06-16 09:25:25,896 - BasicTS-training - INFO - Checkpoint checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\PatchTSTForForecasting_5.pt saved
2026-06-16 09:25:25,905 - BasicTS-training - INFO - The training finished at 2026-06-16 09:25:25
2026-06-16 09:25:25,906 - BasicTS-training - INFO - Evaluating the best model on the test set.
2026-06-16 09:25:25,907 - BasicTS-training - INFO - Loading Checkpoint from 'checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\PatchTSTForForecasting_best_val_MAE.pt'
100%|██████████| 87/87 [00:01<00:00, 55.01it/s]
2026-06-16 09:25:27,512 - BasicTS-training - INFO - Result <test>: [test/time: 1.58 (s), test/loss: 0.3301, test/MAE: 0.3301, test/MSE: 0.2800, test/RMSE: 0.5292, test/MAPE: 9.0062, test/WAPE: 0.5611]
2026-06-16 09:25:27,513 - BasicTS-training - INFO - Test results saved to checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\test_results.
2026-06-16 09:25:27,514 - BasicTS-training - INFO - Test metrics saved to checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\test_metrics.json.
2026-06-16 09:25:27,516 - BasicTS-launcher - INFO - Launching BasicTS evaluation.
2026-06-16 09:25:27,518 - BasicTS - INFO - Building model.
2026-06-16 09:25:27,523 - BasicTS - INFO - Set ckpt save dir: "checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3"
2026-06-16 09:25:27,524 - BasicTS-evaluation - INFO - Loading Checkpoint from 'checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\PatchTSTForForecasting_best_val_MAE.pt'
2026-06-16 09:25:27,535 - BasicTS-evaluation - INFO - Building test data loader.
100%|██████████| 87/87 [00:01<00:00, 61.87it/s]
2026-06-16 09:25:28,944 - BasicTS-evaluation - INFO - Result <test>: [test/time: 1.41 (s), test/loss: 0.3301, test/MAE: 0.3301, test/MSE: 0.2800, test/RMSE: 0.5292, test/MAPE: 9.0062, test/WAPE: 0.5611]
2026-06-16 09:25:28,944 - BasicTS-evaluation - INFO - Test results saved to checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\test_results.
2026-06-16 09:25:28,946 - BasicTS-evaluation - INFO - Test metrics saved to checkpoints\benchmark\PatchTST\ETTh1_96_12\3e81bc4114ae9339f74cb900b5f999d3\test_metrics.json.

Benchmark finished. Results saved to results/

In [4]:
# Display final ranking and failures
import pandas as pd
results_csv = Path("results/model_benchmark_results.csv")
if results_csv.exists():
	df = pd.read_csv(results_csv)
	display(df.sort_values(["MAE", "MSE"], na_position="last"))
else:
	print("No successful model results found.")

failed_csv = Path("results/model_benchmark_failed.csv")
if failed_csv.exists():
	failed_df = pd.read_csv(failed_csv)
	print("\nFailed models:")
	display(failed_df)
else:
	print("No failures recorded.")

,model,MAE,MSE,RMSE,MAPE,WAPE,metrics_file,ckpt_dir
0,iTransformer,0.326405,0.272133,0.521664,8.672733,0.554847,checkpoints\benchmark\iTransformer\ETTh1_96_12...,checkpoints\benchmark\iTransformer\ETTh1_96_12
1,PatchTST,0.330091,0.280017,0.529167,9.006214,0.561137,checkpoints\benchmark\PatchTST\ETTh1_96_12\3e8...,checkpoints\benchmark\PatchTST\ETTh1_96_12
2,DLinear,0.331306,0.282716,0.531711,8.372759,0.557269,checkpoints\benchmark\DLinear\ETTh1_96_12\1e0a...,checkpoints\benchmark\DLinear\ETTh1_96_12
3,NLinear,0.335885,0.289058,0.537642,8.959574,0.568305,checkpoints\benchmark\NLinear\ETTh1_96_12\5484...,checkpoints\benchmark\NLinear\ETTh1_96_12
4,MTSMixer,0.366557,0.325800,0.570789,9.814173,0.605643,checkpoints\benchmark\MTSMixer\ETTh1_96_12\07a...,checkpoints\benchmark\MTSMixer\ETTh1_96_12

Failed models:

      model                                              error
0  TimesNet  train error: TimesNetForForecasting.forward() ...