# Router Model Results

This notebook displays the router test results saved under `results/best_*` and the combined summary file `results/router_model_results_summary.csv`.

In [6]:
from pathlib import Path
import pandas as pd

try:
    from IPython.display import display
except Exception:
    def display(value):
        print(value)

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent

summary_path = ROOT / "results" / "router_model_results_summary.csv"
router_results_df = pd.read_csv(summary_path)

print(f"Loaded {len(router_results_df)} result rows from {summary_path}")
display(router_results_df)

Loaded 31 result rows from c:\Users\luwil\OneDrive\Documents\Code\BasicTS\results\router_model_results_summary.csv

,model_count,model_group,selected_models,method,test_mae,test_mse,test_rmse
0,1,best_1_expert,DLinear,DLinear,0.347951,0.331419,0.575690
1,2,best_2_experts,DLinear + TimesNet,Fixed validation-based soft weights,0.340855,0.320081,0.565757
2,2,best_2_experts,DLinear + TimesNet,Fixed equal average,0.340907,0.320136,0.565806
3,2,best_2_experts,DLinear + TimesNet,Learned prediction-aware router,0.347806,0.327268,0.572074
4,2,best_2_experts,DLinear + TimesNet,DLinear,0.347951,0.331419,0.575690
5,2,best_2_experts,DLinear + TimesNet,Validation-selected best expert,0.347951,0.331419,0.575690
6,2,best_2_experts,DLinear + TimesNet,TimesNet,0.366520,0.352346,0.593588
7,3,best_3_experts,DLinear + iTransformer + ModernTCN,Learned prediction-aware router,0.338889,0.309635,0.556448
8,3,best_3_experts,DLinear + iTransformer + ModernTCN,Fixed validation-based soft weights,0.342275,0.312099,0.558658
9,3,best_3_experts,DLinear + iTransformer + ModernTCN,Fixed equal average,0.342925,0.312688,0.559185
10,3,best_3_experts,DLinear + iTransformer + ModernTCN,DLinear,0.347951,0.331419,0.575690
11,3,best_3_experts,DLinear + iTransformer + ModernTCN,ModernTCN,0.351190,0.322122,0.567558
12,3,best_3_experts,DLinear + iTransformer + ModernTCN,Validation-selected best expert,0.351190,0.322122,0.567558
13,3,best_3_experts,DLinear + iTransformer + ModernTCN,iTransformer,0.400857,0.375451,0.612741
14,4,best_4_experts,DLinear + iTransformer + TimesNet + ModernTCN,Learned prediction-aware router,0.338982,0.310926,0.557607
15,4,best_4_experts,DLinear + iTransformer + TimesNet + ModernTCN,Fixed validation-based soft weights,0.339045,0.310486,0.557212
16,4,best_4_experts,DLinear + iTransformer + TimesNet + ModernTCN,Fixed equal average,0.339541,0.310911,0.557594
17,4,best_4_experts,DLinear + iTransformer + TimesNet + ModernTCN,DLinear,0.347951,0.331419,0.575690
18,4,best_4_experts,DLinear + iTransformer + TimesNet + ModernTCN,ModernTCN,0.351190,0.322122,0.567558
19,4,best_4_experts,DLinear + iTransformer + TimesNet + ModernTCN,Validation-selected best expert,0.351190,0.322122,0.567558
20,4,best_4_experts,DLinear + iTransformer + TimesNet + ModernTCN,TimesNet,0.366520,0.352346,0.593588
21,4,best_4_experts,DLinear + iTransformer + TimesNet + ModernTCN,iTransformer,0.400857,0.375451,0.612741
22,5,best_5_experts,DLinear + PatchTST + iTransformer + TimesNet +...,Fixed validation-based soft weights,0.339299,0.310752,0.557451
23,5,best_5_experts,DLinear + PatchTST + iTransformer + TimesNet +...,Fixed equal average,0.339679,0.311100,0.557763
24,5,best_5_experts,DLinear + PatchTST + iTransformer + TimesNet +...,Learned prediction-aware router,0.340320,0.315812,0.561972
25,5,best_5_experts,DLinear + PatchTST + iTransformer + TimesNet +...,DLinear,0.347951,0.331419,0.575690
26,5,best_5_experts,DLinear + PatchTST + iTransformer + TimesNet +...,ModernTCN,0.351190,0.322122,0.567558
27,5,best_5_experts,DLinear + PatchTST + iTransformer + TimesNet +...,Validation-selected best expert,0.351190,0.322122,0.567558
28,5,best_5_experts,DLinear + PatchTST + iTransformer + TimesNet +...,PatchTST,0.363931,0.336094,0.579736
29,5,best_5_experts,DLinear + PatchTST + iTransformer + TimesNet +...,TimesNet,0.366520,0.352346,0.593588
30,5,best_5_experts,DLinear + PatchTST + iTransformer + TimesNet +...,iTransformer,0.400857,0.375451,0.612741

## Best Method Per Model Count

In [7]:
best_by_group_df = (
    router_results_df.sort_values(["model_count", "test_mae"])
    .groupby("model_count", as_index=False)
    .first()
)
display(best_by_group_df[["model_count", "selected_models", "method", "test_mae", "test_mse", "test_rmse"]])

,model_count,selected_models,method,test_mae,test_mse,test_rmse
0,1,DLinear,DLinear,0.347951,0.331419,0.575690
1,2,DLinear + TimesNet,Fixed validation-based soft weights,0.340855,0.320081,0.565757
2,3,DLinear + iTransformer + ModernTCN,Learned prediction-aware router,0.338889,0.309635,0.556448
3,4,DLinear + iTransformer + TimesNet + ModernTCN,Learned prediction-aware router,0.338982,0.310926,0.557607
4,5,DLinear + PatchTST + iTransformer + TimesNet +...,Fixed validation-based soft weights,0.339299,0.310752,0.557451

## Learned Router Only

In [8]:
learned_router_df = router_results_df[
    router_results_df["method"].eq("Learned prediction-aware router")
].sort_values("test_mae")
display(learned_router_df[["model_count", "selected_models", "test_mae", "test_mse", "test_rmse"]])

,model_count,selected_models,test_mae,test_mse,test_rmse
7,3,DLinear + iTransformer + ModernTCN,0.338889,0.309635,0.556448
14,4,DLinear + iTransformer + TimesNet + ModernTCN,0.338982,0.310926,0.557607
24,5,DLinear + PatchTST + iTransformer + TimesNet +...,0.340320,0.315812,0.561972
3,2,DLinear + TimesNet,0.347806,0.327268,0.572074

## Overall Ranking

In [9]:
overall_ranking_df = router_results_df.sort_values("test_mae", ignore_index=True)
display(overall_ranking_df[["model_count", "selected_models", "method", "test_mae", "test_mse", "test_rmse"]])

,model_count,selected_models,method,test_mae,test_mse,test_rmse
0,3,DLinear + iTransformer + ModernTCN,Learned prediction-aware router,0.338889,0.309635,0.556448
1,4,DLinear + iTransformer + TimesNet + ModernTCN,Learned prediction-aware router,0.338982,0.310926,0.557607
2,4,DLinear + iTransformer + TimesNet + ModernTCN,Fixed validation-based soft weights,0.339045,0.310486,0.557212
3,5,DLinear + PatchTST + iTransformer + TimesNet +...,Fixed validation-based soft weights,0.339299,0.310752,0.557451
4,4,DLinear + iTransformer + TimesNet + ModernTCN,Fixed equal average,0.339541,0.310911,0.557594
5,5,DLinear + PatchTST + iTransformer + TimesNet +...,Fixed equal average,0.339679,0.311100,0.557763
6,5,DLinear + PatchTST + iTransformer + TimesNet +...,Learned prediction-aware router,0.340320,0.315812,0.561972
7,2,DLinear + TimesNet,Fixed validation-based soft weights,0.340855,0.320081,0.565757
8,2,DLinear + TimesNet,Fixed equal average,0.340907,0.320136,0.565806
9,3,DLinear + iTransformer + ModernTCN,Fixed validation-based soft weights,0.342275,0.312099,0.558658
10,3,DLinear + iTransformer + ModernTCN,Fixed equal average,0.342925,0.312688,0.559185
11,2,DLinear + TimesNet,Learned prediction-aware router,0.347806,0.327268,0.572074
12,3,DLinear + iTransformer + ModernTCN,DLinear,0.347951,0.331419,0.575690
13,2,DLinear + TimesNet,Validation-selected best expert,0.347951,0.331419,0.575690
14,2,DLinear + TimesNet,DLinear,0.347951,0.331419,0.575690
15,1,DLinear,DLinear,0.347951,0.331419,0.575690
16,5,DLinear + PatchTST + iTransformer + TimesNet +...,DLinear,0.347951,0.331419,0.575690
17,4,DLinear + iTransformer + TimesNet + ModernTCN,DLinear,0.347951,0.331419,0.575690
18,3,DLinear + iTransformer + ModernTCN,ModernTCN,0.351190,0.322122,0.567558
19,3,DLinear + iTransformer + ModernTCN,Validation-selected best expert,0.351190,0.322122,0.567558
20,5,DLinear + PatchTST + iTransformer + TimesNet +...,ModernTCN,0.351190,0.322122,0.567558
21,5,DLinear + PatchTST + iTransformer + TimesNet +...,Validation-selected best expert,0.351190,0.322122,0.567558
22,4,DLinear + iTransformer + TimesNet + ModernTCN,Validation-selected best expert,0.351190,0.322122,0.567558
23,4,DLinear + iTransformer + TimesNet + ModernTCN,ModernTCN,0.351190,0.322122,0.567558
24,5,DLinear + PatchTST + iTransformer + TimesNet +...,PatchTST,0.363931,0.336094,0.579736
25,2,DLinear + TimesNet,TimesNet,0.366520,0.352346,0.593588
26,5,DLinear + PatchTST + iTransformer + TimesNet +...,TimesNet,0.366520,0.352346,0.593588
27,4,DLinear + iTransformer + TimesNet + ModernTCN,TimesNet,0.366520,0.352346,0.593588
28,3,DLinear + iTransformer + ModernTCN,iTransformer,0.400857,0.375451,0.612741
29,4,DLinear + iTransformer + TimesNet + ModernTCN,iTransformer,0.400857,0.375451,0.612741
30,5,DLinear + PatchTST + iTransformer + TimesNet +...,iTransformer,0.400857,0.375451,0.612741

## Source Result Files

In [10]:
source_files = sorted((ROOT / "results").glob("best_*/router_test_comparison.csv"))
for path in source_files:
    print(path.relative_to(ROOT))

results\best_1_expert\router_test_comparison.csv
results\best_2_experts\router_test_comparison.csv
results\best_3_experts\router_test_comparison.csv
results\best_4_experts\router_test_comparison.csv
results\best_5_experts\router_test_comparison.csv